name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    environment:
      name: nuget
      url: https://www.nuget.org/packages/KbitFont
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "8.0.x"
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet pack
      - name: Publish
        run: dotnet nuget push ./src/KbitSpec/bin/Release/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
